### ISSUE TITLE
Could not find SS2040FL on pcb

### ISSUE THREAD

**Issue by BenRoe** [eswai/7x4x2#1]
Hello,
thanks for this open source bl board.
I checked the mid pcb and could not find the (40V2A)SS2040FL, but it's mentioned in the bom.

**Comment by eswai** [comment]
They are located as D1 and D2 between two battery holders.

**Comment by BenRoe** [comment]
My bad, thought these are normal diodes.
Btw do already tested the pcb?

**Comment by BenRoe** [comment]
I also get a "Audit fail" at jlcpcb, because "the spacing between slot to slot or outline require 3mm at least in case of break off , kindly replace with new file ."
I never had a problem with that, but since one week i get this error.

**Comment by eswai** [comment]
JLCPCB actually produced the PCB for me two weeks ago without any issues. The keyboard works fine.
